# Generated by Django 2.1.4 on 2018-12-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_no', models.CharField(max_length=5, unique=True)),
                ('image', models.ImageField(upload_to='clothes')),
                ('date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['model_no'],
            },
        ),
        migrations.CreateModel(
            name='ClothesCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('about', models.TextField(blank=True, max_length=400)),
            ],
            options={
                'verbose_name_plural': 'Clothes Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Qualities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'qualities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('14L', '14L'), ('15L', '15L'), ('16L', '16L'), ('17L', '17L'), ('18L', '18L'), ('19L', '19L'), ('20L', '20L'), ('21L', '21L'), ('22L', '22L'), ('23L', '23L'), ('24L', '24L'), ('25L', '25L'), ('26L', '26L'), ('27L', '27L'), ('28L', '28L'), ('29L', '29L'), ('30L', '30L'), ('31L', '31L'), ('32L', '32L'), ('33L', '33L'), ('34L', '34L'), ('35L', '35L'), ('36L', '36L')], default='14L', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'sizes',
                'ordering': ['size'],
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'verbose_name_plural': 'tags',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='clothes',
            name='button_type',
            field=models.ManyToManyField(related_name='clothes_category', to='clothes.ClothesCategory'),
        ),
        migrations.AddField(
            model_name='clothes',
            name='qualities',
            field=models.ManyToManyField(blank=True, related_name='qualities', to='clothes.Qualities'),
        ),
        migrations.AddField(
            model_name='clothes',
            name='size',
            field=models.ManyToManyField(related_name='sizes', to='clothes.Sizes'),
        ),
        migrations.AddField(
            model_name='clothes',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='clothes.Tags'),
        ),
    ]
