# Generated by Django 2.1.4 on 2018-12-30 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothes',
            old_name='button_type',
            new_name='cloth_category',
        ),
    ]
